CREATE TABLE "top_chess_players" (
	"fide_id" integer PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"age" integer NOT NULL,
	"flag" varchar(2) NOT NULL,
	"country_name" text NOT NULL,
	"birthday" date,
	"standard_rating" real NOT NULL,
	"rapid_rating" real,
	"blitz_rating" real,
	"rapid_rating_inactive" boolean DEFAULT false NOT NULL,
	"blitz_rating_inactive" boolean DEFAULT false NOT NULL,
	"standard_rank" integer NOT NULL,
	"rapid_rank" integer,
	"blitz_rank" integer,
	"standard_junior_rank" integer,
	"rapid_junior_rank" integer,
	"blitz_junior_rank" integer,
	"standard_u16_rank" integer,
	"rapid_u16_rank" integer,
	"blitz_u16_rank" integer,
	"standard_best_rank_title" text NOT NULL,
	"standard_best_rating_title" text NOT NULL,
	"rapid_best_rating_title" text,
	"blitz_best_rating_title" text,
	"standard_month_rating_change" real NOT NULL,
	"standard_month_rank_change" integer NOT NULL,
	"standard_year_rating_change" real NOT NULL,
	"standard_year_rank_change" integer NOT NULL,
	"standard_rating_history" integer[] NOT NULL,
	"has_live_standard_game" boolean NOT NULL,
	"has_live_rapid_game" boolean NOT NULL,
	"has_live_blitz_game" boolean NOT NULL,
	"recent_standard_games_count" integer NOT NULL,
	"recent_rapid_games_count" integer NOT NULL,
	"recent_blitz_games_count" integer NOT NULL,
	"standard_last_update" timestamp with time zone,
	"rapid_last_update" timestamp with time zone,
	"blitz_last_update" timestamp with time zone,
	"wikipedia_url" text,
	"image_url" text,
	"bio" text,
	"description" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
