type CountryInfo = {
  alpha2: string;
  name: string;
};

const countries: Record<string, CountryInfo> = {
  afg: { alpha2: "af", name: "Afghanistan" },
  ala: { alpha2: "ax", name: "Åland Islands" },
  alb: { alpha2: "al", name: "Albania" },
  dza: { alpha2: "dz", name: "Algeria" },
  asm: { alpha2: "as", name: "American Samoa" },
  and: { alpha2: "ad", name: "Andorra" },
  ago: { alpha2: "ao", name: "Angola" },
  aia: { alpha2: "ai", name: "Anguilla" },
  ata: { alpha2: "aq", name: "Antarctica" },
  atg: { alpha2: "ag", name: "Antigua and Barbuda" },
  arg: { alpha2: "ar", name: "Argentina" },
  arm: { alpha2: "am", name: "Armenia" },
  abw: { alpha2: "aw", name: "Aruba" },
  aus: { alpha2: "au", name: "Australia" },
  aut: { alpha2: "at", name: "Austria" },
  aze: { alpha2: "az", name: "Azerbaijan" },
  bhs: { alpha2: "bs", name: "Bahamas" },
  bhr: { alpha2: "bh", name: "Bahrain" },
  bgd: { alpha2: "bd", name: "Bangladesh" },
  brb: { alpha2: "bb", name: "Barbados" },
  blr: { alpha2: "by", name: "Belarus" },
  bel: { alpha2: "be", name: "Belgium" },
  blz: { alpha2: "bz", name: "Belize" },
  ben: { alpha2: "bj", name: "Benin" },
  bmu: { alpha2: "bm", name: "Bermuda" },
  btn: { alpha2: "bt", name: "Bhutan" },
  bol: { alpha2: "bo", name: "Bolivia" },
  bes: { alpha2: "bq", name: "Bonaire, Sint Eustatius and Saba" },
  bih: { alpha2: "ba", name: "Bosnia and Herzegovina" },
  bwa: { alpha2: "bw", name: "Botswana" },
  bvt: { alpha2: "bv", name: "Bouvet Island" },
  bra: { alpha2: "br", name: "Brazil" },
  iot: { alpha2: "io", name: "British Indian Ocean Territory" },
  brn: { alpha2: "bn", name: "Brunei" },
  bgr: { alpha2: "bg", name: "Bulgaria" },
  bfa: { alpha2: "bf", name: "Burkina Faso" },
  bdi: { alpha2: "bi", name: "Burundi" },
  cpv: { alpha2: "cv", name: "Cabo Verde" },
  khm: { alpha2: "kh", name: "Cambodia" },
  cmr: { alpha2: "cm", name: "Cameroon" },
  can: { alpha2: "ca", name: "Canada" },
  cym: { alpha2: "ky", name: "Cayman Islands" },
  caf: { alpha2: "cf", name: "Central African Republic" },
  tcd: { alpha2: "td", name: "Chad" },
  chl: { alpha2: "cl", name: "Chile" },
  chn: { alpha2: "cn", name: "China" },
  cxr: { alpha2: "cx", name: "Christmas Island" },
  cck: { alpha2: "cc", name: "Cocos (Keeling) Islands" },
  col: { alpha2: "co", name: "Colombia" },
  com: { alpha2: "km", name: "Comoros" },
  cog: { alpha2: "cg", name: "Congo" },
  cod: { alpha2: "cd", name: "Congo, Democratic Republic" },
  cok: { alpha2: "ck", name: "Cook Islands" },
  cri: { alpha2: "cr", name: "Costa Rica" },
  civ: { alpha2: "ci", name: "Côte d'Ivoire" },
  hrv: { alpha2: "hr", name: "Croatia" },
  cub: { alpha2: "cu", name: "Cuba" },
  cuw: { alpha2: "cw", name: "Curaçao" },
  cyp: { alpha2: "cy", name: "Cyprus" },
  cze: { alpha2: "cz", name: "Czech Republic" },
  dnk: { alpha2: "dk", name: "Denmark" },
  dji: { alpha2: "dj", name: "Djibouti" },
  dma: { alpha2: "dm", name: "Dominica" },
  dom: { alpha2: "do", name: "Dominican Republic" },
  ecu: { alpha2: "ec", name: "Ecuador" },
  egy: { alpha2: "eg", name: "Egypt" },
  slv: { alpha2: "sv", name: "El Salvador" },
  gnq: { alpha2: "gq", name: "Equatorial Guinea" },
  eri: { alpha2: "er", name: "Eritrea" },
  est: { alpha2: "ee", name: "Estonia" },
  swz: { alpha2: "sz", name: "Eswatini" },
  eth: { alpha2: "et", name: "Ethiopia" },
  flk: { alpha2: "fk", name: "Falkland Islands" },
  fro: { alpha2: "fo", name: "Faroe Islands" },
  fji: { alpha2: "fj", name: "Fiji" },
  fin: { alpha2: "fi", name: "Finland" },
  fra: { alpha2: "fr", name: "France" },
  guf: { alpha2: "gf", name: "French Guiana" },
  pyf: { alpha2: "pf", name: "French Polynesia" },
  atf: { alpha2: "tf", name: "French Southern Territories" },
  gab: { alpha2: "ga", name: "Gabon" },
  gmb: { alpha2: "gm", name: "Gambia" },
  geo: { alpha2: "ge", name: "Georgia" },
  deu: { alpha2: "de", name: "Germany" },
  gha: { alpha2: "gh", name: "Ghana" },
  gib: { alpha2: "gi", name: "Gibraltar" },
  grc: { alpha2: "gr", name: "Greece" },
  grl: { alpha2: "gl", name: "Greenland" },
  grd: { alpha2: "gd", name: "Grenada" },
  glp: { alpha2: "gp", name: "Guadeloupe" },
  gum: { alpha2: "gu", name: "Guam" },
  gtm: { alpha2: "gt", name: "Guatemala" },
  ggg: { alpha2: "gg", name: "Guernsey" },
  gin: { alpha2: "gn", name: "Guinea" },
  gnb: { alpha2: "gw", name: "Guinea-Bissau" },
  guy: { alpha2: "gy", name: "Guyana" },
  hti: { alpha2: "ht", name: "Haiti" },
  hmd: { alpha2: "hm", name: "Heard Island and McDonald Islands" },
  vat: { alpha2: "va", name: "Holy See" },
  hnd: { alpha2: "hn", name: "Honduras" },
  hkg: { alpha2: "hk", name: "Hong Kong" },
  hun: { alpha2: "hu", name: "Hungary" },
  isl: { alpha2: "is", name: "Iceland" },
  ind: { alpha2: "in", name: "India" },
  idn: { alpha2: "id", name: "Indonesia" },
  irn: { alpha2: "ir", name: "Iran" },
  irq: { alpha2: "iq", name: "Iraq" },
  irl: { alpha2: "ie", name: "Ireland" },
  imn: { alpha2: "im", name: "Isle of Man" },
  isr: { alpha2: "il", name: "Israel" },
  ita: { alpha2: "it", name: "Italy" },
  jam: { alpha2: "jm", name: "Jamaica" },
  jpn: { alpha2: "jp", name: "Japan" },
  jey: { alpha2: "je", name: "Jersey" },
  jor: { alpha2: "jo", name: "Jordan" },
  kaz: { alpha2: "kz", name: "Kazakhstan" },
  ken: { alpha2: "ke", name: "Kenya" },
  kir: { alpha2: "ki", name: "Kiribati" },
  prk: { alpha2: "kp", name: "North Korea" },
  kor: { alpha2: "kr", name: "South Korea" },
  kwt: { alpha2: "kw", name: "Kuwait" },
  kgz: { alpha2: "kg", name: "Kyrgyzstan" },
  lao: { alpha2: "la", name: "Laos" },
  lva: { alpha2: "lv", name: "Latvia" },
  lbn: { alpha2: "lb", name: "Lebanon" },
  lso: { alpha2: "ls", name: "Lesotho" },
  lbr: { alpha2: "lr", name: "Liberia" },
  lby: { alpha2: "ly", name: "Libya" },
  lie: { alpha2: "li", name: "Liechtenstein" },
  ltu: { alpha2: "lt", name: "Lithuania" },
  lux: { alpha2: "lu", name: "Luxembourg" },
  mac: { alpha2: "mo", name: "Macao" },
  mdg: { alpha2: "mg", name: "Madagascar" },
  mwi: { alpha2: "mw", name: "Malawi" },
  mys: { alpha2: "my", name: "Malaysia" },
  mdv: { alpha2: "mv", name: "Maldives" },
  mli: { alpha2: "ml", name: "Mali" },
  mlt: { alpha2: "mt", name: "Malta" },
  mhl: { alpha2: "mh", name: "Marshall Islands" },
  mtq: { alpha2: "mq", name: "Martinique" },
  mrt: { alpha2: "mr", name: "Mauritania" },
  mus: { alpha2: "mu", name: "Mauritius" },
  myt: { alpha2: "yt", name: "Mayotte" },
  mex: { alpha2: "mx", name: "Mexico" },
  fsm: { alpha2: "fm", name: "Micronesia" },
  mda: { alpha2: "md", name: "Moldova" },
  mco: { alpha2: "mc", name: "Monaco" },
  mng: { alpha2: "mn", name: "Mongolia" },
  mne: { alpha2: "me", name: "Montenegro" },
  msr: { alpha2: "ms", name: "Montserrat" },
  mar: { alpha2: "ma", name: "Morocco" },
  moz: { alpha2: "mz", name: "Mozambique" },
  mmr: { alpha2: "mm", name: "Myanmar" },
  nam: { alpha2: "na", name: "Namibia" },
  nru: { alpha2: "nr", name: "Nauru" },
  npl: { alpha2: "np", name: "Nepal" },
  nld: { alpha2: "nl", name: "Netherlands" },
  ncl: { alpha2: "nc", name: "New Caledonia" },
  nzl: { alpha2: "nz", name: "New Zealand" },
  nic: { alpha2: "ni", name: "Nicaragua" },
  ner: { alpha2: "ne", name: "Niger" },
  nga: { alpha2: "ng", name: "Nigeria" },
  niu: { alpha2: "nu", name: "Niue" },
  nfk: { alpha2: "nf", name: "Norfolk Island" },
  mkd: { alpha2: "mk", name: "North Macedonia" },
  mnp: { alpha2: "mp", name: "Northern Mariana Islands" },
  nor: { alpha2: "no", name: "Norway" },
  omn: { alpha2: "om", name: "Oman" },
  pak: { alpha2: "pk", name: "Pakistan" },
  plw: { alpha2: "pw", name: "Palau" },
  pse: { alpha2: "ps", name: "Palestine" },
  pan: { alpha2: "pa", name: "Panama" },
  png: { alpha2: "pg", name: "Papua New Guinea" },
  pry: { alpha2: "py", name: "Paraguay" },
  per: { alpha2: "pe", name: "Peru" },
  phl: { alpha2: "ph", name: "Philippines" },
  pcn: { alpha2: "pn", name: "Pitcairn" },
  pol: { alpha2: "pl", name: "Poland" },
  prt: { alpha2: "pt", name: "Portugal" },
  pri: { alpha2: "pr", name: "Puerto Rico" },
  qat: { alpha2: "qa", name: "Qatar" },
  reu: { alpha2: "re", name: "Réunion" },
  rou: { alpha2: "ro", name: "Romania" },
  rus: { alpha2: "ru", name: "Russia" },
  rwa: { alpha2: "rw", name: "Rwanda" },
  blm: { alpha2: "bl", name: "Saint Barthélemy" },
  shn: { alpha2: "sh", name: "Saint Helena" },
  kna: { alpha2: "kn", name: "Saint Kitts and Nevis" },
  lca: { alpha2: "lc", name: "Saint Lucia" },
  maf: { alpha2: "mf", name: "Saint Martin" },
  spm: { alpha2: "pm", name: "Saint Pierre and Miquelon" },
  vct: { alpha2: "vc", name: "Saint Vincent and the Grenadines" },
  wsm: { alpha2: "ws", name: "Samoa" },
  smr: { alpha2: "sm", name: "San Marino" },
  stp: { alpha2: "st", name: "Sao Tome and Principe" },
  sau: { alpha2: "sa", name: "Saudi Arabia" },
  sen: { alpha2: "sn", name: "Senegal" },
  srb: { alpha2: "rs", name: "Serbia" },
  syc: { alpha2: "sc", name: "Seychelles" },
  sle: { alpha2: "sl", name: "Sierra Leone" },
  sgp: { alpha2: "sg", name: "Singapore" },
  sxm: { alpha2: "sx", name: "Sint Maarten" },
  svk: { alpha2: "sk", name: "Slovakia" },
  svn: { alpha2: "si", name: "Slovenia" },
  slb: { alpha2: "sb", name: "Solomon Islands" },
  som: { alpha2: "so", name: "Somalia" },
  zaf: { alpha2: "za", name: "South Africa" },
  sgs: { alpha2: "gs", name: "South Georgia" },
  ssd: { alpha2: "ss", name: "South Sudan" },
  esp: { alpha2: "es", name: "Spain" },
  lka: { alpha2: "lk", name: "Sri Lanka" },
  sdn: { alpha2: "sd", name: "Sudan" },
  sur: { alpha2: "sr", name: "Suriname" },
  sjm: { alpha2: "sj", name: "Svalbard and Jan Mayen" },
  swe: { alpha2: "se", name: "Sweden" },
  che: { alpha2: "ch", name: "Switzerland" },
  syr: { alpha2: "sy", name: "Syria" },
  twn: { alpha2: "tw", name: "Taiwan" },
  tjk: { alpha2: "tj", name: "Tajikistan" },
  tza: { alpha2: "tz", name: "Tanzania" },
  tha: { alpha2: "th", name: "Thailand" },
  tls: { alpha2: "tl", name: "Timor-Leste" },
  tgo: { alpha2: "tg", name: "Togo" },
  tkl: { alpha2: "tk", name: "Tokelau" },
  ton: { alpha2: "to", name: "Tonga" },
  tto: { alpha2: "tt", name: "Trinidad and Tobago" },
  tun: { alpha2: "tn", name: "Tunisia" },
  tur: { alpha2: "tr", name: "Turkey" },
  tkm: { alpha2: "tm", name: "Turkmenistan" },
  tca: { alpha2: "tc", name: "Turks and Caicos Islands" },
  tuv: { alpha2: "tv", name: "Tuvalu" },
  uga: { alpha2: "ug", name: "Uganda" },
  ukr: { alpha2: "ua", name: "Ukraine" },
  are: { alpha2: "ae", name: "United Arab Emirates" },
  gbr: { alpha2: "gb", name: "United Kingdom" },
  usa: { alpha2: "us", name: "United States" },
  umi: { alpha2: "um", name: "U.S. Minor Outlying Islands" },
  ury: { alpha2: "uy", name: "Uruguay" },
  uzb: { alpha2: "uz", name: "Uzbekistan" },
  vut: { alpha2: "vu", name: "Vanuatu" },
  ven: { alpha2: "ve", name: "Venezuela" },
  vnm: { alpha2: "vn", name: "Vietnam" },
  vgb: { alpha2: "vg", name: "Virgin Islands (British)" },
  vir: { alpha2: "vi", name: "Virgin Islands (U.S.)" },
  wlf: { alpha2: "wf", name: "Wallis and Futuna" },
  esh: { alpha2: "eh", name: "Western Sahara" },
  yem: { alpha2: "ye", name: "Yemen" },
  zmb: { alpha2: "zm", name: "Zambia" },
  zwe: { alpha2: "zw", name: "Zimbabwe" },
};

export function getCountryInfo(alpha3: string): CountryInfo | null {
  return countries[alpha3.toLowerCase()] ?? null;
}

export function flagStringToEmoji(flagString: string) {
  return flagString
    .toUpperCase()
    .split("")
    .map((char) => String.fromCodePoint(0x1f1e6 - 65 + char.charCodeAt(0)))
    .join("");
}
